language: python

git:
  depth: false

addons:
  apt:
    packages:
    - tree

branches:
  only:
  - master
  - develop
  - "/^v\\d+\\.\\d+\\.\\d+(-S*)?$/"
  - "/.*\\/(?i:build)$/"

before_install:
- eval "$(ssh-agent -s)"
- openssl aes-256-cbc -K $encrypted_59dd47104fb2_key -iv $encrypted_59dd47104fb2_iv
  -in deploy_key.enc -out ./deploy_key -d
- chmod 600 ./deploy_key
- ssh-add ./deploy_key

jobs:
  include:
  - stage: build docs
    script:
    - echo $(if [[ "$TRAVIS_BRANCH" == "develop" || "$TRAVIS_BRANCH" == "master" ]]; then echo "$TRAVIS_BRANCH"; elif [[ ! -z "$TRAVIS_TAG" ]]; then echo "tags/$TRAVIS_TAG"; else echo "branches/$(echo $TRAVIS_BRANCH | tr / _ | tr - .)"; fi) | tee /tmp/output_location
    - echo "output to: $(cat /tmp/output_location)"
    - make html
    - ls ./build/html
    - echo "ultimate output location is $(cat /tmp/output_location)"
    - mv ./build/html /tmp/build.html
    - git checkout gh-pages
    - git clean -d -f -x
    - ls
    - rsync -av --delete /tmp/build.html/ ./$(cat /tmp/output_location)
    - tree -L 2
    - git status
