language: python

git:
  # override the default `--depth 50`
  depth: false

branches:
  only:
    - master
    - develop
    # build tags which start with "v", have a semantic version, and then optionall a "-" followed by a string
    - /^v\d+\.\d+\.\d+(-S*)?$/
    # build branches which end in "/build"
    - /.*\/(?i:build)$/
jobs:
  include:
    - stage: build docs
      script:
        - make html
        - ls ./build/html
        - mv ./build/html /tmp/$(echo ${TRAVIS_BRANCH} | tr / _)
        - git checkout gh-pages
        - ls
        - rsync -av --delete /tmp/$(echo ${TRAVIS_BRANCH} | tr / _)/ ./$(echo ${TRAVIS_BRANCH} | tr / _)
        - ls
        - git status
